export const agentRuntimeMutationHeaders = {
    origin: 'x-haus-origin',
} as const;

export const agentRuntimeMutationOrigins = {
    haus: 'haus',
    agentRuntime: 'agent-runtime',
} as const;

export const agentRuntimeRoutes = {
    agent: (id: string) => `/agents/${id}`,
    agentConfig: (id: string) => `/agents/${id}/config`,
    agentFile: (agentId: string, path: string) =>
        `/agents/${agentId}/files/${encodeURIComponent(path)}`,
    agentBio: (id: string) => `/agents/${id}/bio`,
    agentFiles: (agentId: string) => `/agents/${agentId}/files`,
    agentModel: (id: string) => `/agents/${id}/model`,
    agentName: (id: string) => `/agents/${id}/name`,
    agentInbox: (id: string) => `/agents/${id}/inbox`,
    agentRestart: (id: string) => `/agents/${id}/restart`,
    agentStop: (id: string) => `/agents/${id}/stop`,
    agentThinkingDefault: (id: string) => `/agents/${id}/thinking-default`,
    agentWebSettings: (id: string) => `/agents/${id}/web-settings`,
    agents: '/agents',
    capabilities: '/capabilities',
    capability: (id: string) => `/capabilities/${encodeURIComponent(id)}`,
    capabilityRefresh: (id: string) => `/capabilities/${encodeURIComponent(id)}/refresh`,
    capabilitiesRefresh: '/capabilities/refresh',
    update: '/update',
    updateRestart: '/update/restart',
    updateStatus: '/update/status',
    macApps: '/mac-apps',
    mcpAgentGrants: (agentId: string) => `/mcp/agents/${encodeURIComponent(agentId)}/grants`,
    mcpAgentHostTools: (agentId: string) => `/mcp/agents/${encodeURIComponent(agentId)}/host-tools`,
    mcpAgentHostToolGrant: (agentId: string, toolId: string) =>
        `/mcp/agents/${encodeURIComponent(agentId)}/host-tools/${encodeURIComponent(toolId)}/grant`,
    mcpAgentToolGrant: (agentId: string, connectionId: string, toolName: string) =>
        `/mcp/agents/${encodeURIComponent(agentId)}/connections/${encodeURIComponent(
            connectionId
        )}/tools/${encodeURIComponent(toolName)}/grant`,
    mcpConnection: (id: string) => `/mcp/connections/${encodeURIComponent(id)}`,
    mcpConnectionDisconnect: (id: string) =>
        `/mcp/connections/${encodeURIComponent(id)}/disconnect`,
    mcpConnectionOAuthComplete: (id: string) =>
        `/mcp/connections/${encodeURIComponent(id)}/oauth/complete`,
    mcpConnectionOAuthStart: (id: string) =>
        `/mcp/connections/${encodeURIComponent(id)}/oauth/start`,
    mcpConnectionRefresh: (id: string) => `/mcp/connections/${encodeURIComponent(id)}/refresh`,
    mcpConnectionTest: (id: string) => `/mcp/connections/${encodeURIComponent(id)}/test`,
    mcpConnectionTools: (id: string) => `/mcp/connections/${encodeURIComponent(id)}/tools`,
    mcpConnections: '/mcp/connections',
    mcpPresetAccounts: '/mcp/preset-accounts',
    modelAccess: '/model-access',
    modelAccessApiKey: '/model-access/api-key',
    modelAccessOAuthCancel: (sessionId: string) =>
        `/model-access/oauth/sessions/${encodeURIComponent(sessionId)}`,
    modelAccessOAuthPoll: (providerId: string, sessionId: string) =>
        `/model-access/oauth/${encodeURIComponent(providerId)}/poll/${encodeURIComponent(sessionId)}`,
    modelAccessOAuthStart: (providerId: string) =>
        `/model-access/oauth/${encodeURIComponent(providerId)}/start`,
    modelAccessOAuthSubmit: (providerId: string) =>
        `/model-access/oauth/${encodeURIComponent(providerId)}/submit`,
    modelAccessOpenAiSettings: '/model-access/openai',
    modelAccessOpenRouterSettings: '/model-access/openrouter',
    modelCapabilitySelections: '/model-capabilities/selections',
    modelCategorySettings: '/model-categories/settings',
    modelProvider: (providerId: string) => `/model-providers/${encodeURIComponent(providerId)}`,
    modelProvidersCatalog: '/model-providers/catalog',
    modelProvidersEnabled: '/model-providers/enabled',
    agentEnv: '/agent-env',
    timezoneSettings: '/timezone/settings',
    identityInvite: (id: string) => `/identity/invites/${encodeURIComponent(id)}`,
    identityInviteRedeem: '/identity/invites/redeem',
    identityInvites: '/identity/invites',
    identityMe: '/identity/me',
    identityMember: (userId: string) => `/identity/members/${encodeURIComponent(userId)}`,
    identityMembers: '/identity/members',
    job: (slug: string) => `/jobs/${encodeURIComponent(slug)}`,
    jobRun: (slug: string) => `/jobs/${encodeURIComponent(slug)}/run`,
    jobs: '/jobs',
    agentEngineConfig: '/agent-engine/config',
    events: '/events',
    chatMessages: (chatId: string) => `/agent/chats/${chatId}/messages`,
    chatAgentSessionCurrent: (chatId: string) =>
        `/agent/chats/${encodeURIComponent(chatId)}/agent-sessions/current`,
    agentSessionReset: (agentId: string) => `/agents/${encodeURIComponent(agentId)}/session/reset`,
    agentPresence: '/agents/presence',
    agentActivity: (agentId: string) => `/agents/${encodeURIComponent(agentId)}/activity`,
    chatTurnStop: (chatId: string, runId: string) =>
        `/agent/chats/${encodeURIComponent(chatId)}/turns/${encodeURIComponent(runId)}/stop`,
    chatPaneState: (chatId: string) => `/agent/chats/${encodeURIComponent(chatId)}/pane-state`,
    chats: '/agent/chats',
    health: '/health',
    workspaceAgentInstructions: (agentId: string) =>
        `/workspace/agents/${encodeURIComponent(agentId)}/instructions`,
    workspaceAgentFile: (agentId: string, path: string) =>
        `/workspace/agents/${encodeURIComponent(agentId)}/files/${encodeURIComponent(path)}`,
    workspaceAgentFiles: (agentId: string) =>
        `/workspace/agents/${encodeURIComponent(agentId)}/files`,
    models: '/models',
    binding: (id: string) => `/bindings/${id}`,
    bindings: '/bindings',
    browserSettings: '/browser/settings',
    discordBinding: (id: string) => `/bindings/discord/${encodeURIComponent(id)}`,
    discordBindings: '/bindings/discord',
    skill: (id: string) => `/skills/${encodeURIComponent(id)}`,
    skillEnabled: (id: string) => `/skills/${id}/enabled`,
    skillReset: (id: string) => `/skills/${encodeURIComponent(id)}/reset`,
    skillHubAvailable: '/skills/hub/available',
    skillHubInstall: '/skills/hub/install',
    skillHubPreview: '/skills/hub/preview',
    skillHubScan: '/skills/hub/scan',
    skillHubTap: (repo: string) => `/skills/hub/taps/${encodeURIComponent(repo)}`,
    skillHubTaps: '/skills/hub/taps',
    skillHubUninstall: '/skills/hub/uninstall',
    skills: '/skills',
    tool: (id: string) => `/tools/${encodeURIComponent(id)}`,
    toolConfig: (id: string) => `/tools/${encodeURIComponent(id)}/config`,
    toolEnabled: (id: string) => `/tools/${encodeURIComponent(id)}/enabled`,
    toolEnv: (id: string) => `/tools/${encodeURIComponent(id)}/env`,
    toolPostSetup: (id: string) => `/tools/${encodeURIComponent(id)}/post-setup`,
    toolProvider: (id: string) => `/tools/${encodeURIComponent(id)}/provider`,
    tools: '/tools',
    sessionGraph: (sessionKey: string) => `/agent/sessions/${sessionKey}/graph`,
    sessionMessages: (sessionKey: string) => `/agent/sessions/${sessionKey}/messages`,
    sessionPrompt: (sessionKey: string) => `/agent/sessions/${sessionKey}/prompt`,
    sessionPreviews: '/agent/sessions/previews',
    sessionResync: (sessionKey: string) => `/agent/sessions/${sessionKey}/resync`,
    sessions: '/agent/sessions',
} as const;
