#!/usr/bin/env bash

# Cleanup runs as an always() workflow step, including after a failed import or
# publisher. Paths are generated by setup-apple-material.sh and persisted via
# GITHUB_ENV for this job only.
set -euo pipefail

cleanup_failed=0
if [[ -n "${HAUS_RELEASE_KEYCHAIN_PATH:-}" && -e "${HAUS_RELEASE_KEYCHAIN_PATH}" ]]; then
  security delete-keychain "${HAUS_RELEASE_KEYCHAIN_PATH}" || cleanup_failed=1
fi
for material_path in \
  "${HAUS_RELEASE_CERTIFICATE_PATH:-}" \
  "${APPLE_API_KEY_PATH:-}" \
  "${HAUS_RELEASE_PROVISIONING_PROFILE_PATH:-}" \
  "${HAUS_RELEASE_NOTIFICATION_SERVICE_PROVISIONING_PROFILE_PATH:-}"; do
  if [[ -n "${material_path}" ]]; then
    rm -f "${material_path}" || cleanup_failed=1
  fi
done
if [[ "${cleanup_failed}" -ne 0 ]]; then
  echo "Apple release material cleanup failed; refusing a clean job result" >&2
  exit 1
fi
