import Foundation
import HausModels

/// One pickable emoji: its fully qualified spelling (the one `ReactionEmoji`
/// sends), its CLDR name, and the words search matches.
struct EmojiEntry: Identifiable, Hashable, Sendable {
    let emoji: String
    let name: String
    /// Name words first, then `emojilib`'s keywords, lowercased.
    let words: [String]
    let supportsSkinTones: Bool

    var id: String { emoji }
}

/// A Unicode emoji group, in Unicode's order.
struct EmojiCategory: Identifiable, Hashable, Sendable {
    let name: String
    let entries: [EmojiEntry]

    var id: String { name }
}

/// The bundled emoji set (`Resources/emoji-catalog.json`, generated by
/// `scripts/generate-emoji-catalog.ts`), cut to what this device draws.
struct EmojiCatalog: Sendable {
    let categories: [EmojiCategory]
    private let index: [String: EmojiEntry]

    init(categories: [EmojiCategory]) {
        self.categories = categories
        index = Dictionary(
            categories.flatMap(\.entries).map { ($0.emoji, $0) },
            uniquingKeysWith: { first, _ in first }
        )
    }

    /// Decoded once; the file is ~160 KB.
    static let shared = EmojiCatalog.bundled(maxVersion: EmojiCatalog.deviceEmojiVersion)

    /// The newest Emoji version this OS draws: iOS 18.4 brought Emoji 16.0 and
    /// iOS 26.4 Emoji 17.0. Anything newer would render as a missing glyph.
    static var deviceEmojiVersion: Double {
        #if os(iOS)
        if #available(iOS 26.4, *) { return 17.0 }
        if #available(iOS 18.4, *) { return 16.0 }
        return 15.1
        #else
        return 17.0
        #endif
    }

    static func bundled(maxVersion: Double) -> EmojiCatalog {
        guard let url = Bundle.module.url(forResource: "emoji-catalog", withExtension: "json"),
              let data = try? Data(contentsOf: url, options: .mappedIfSafe),
              let catalog = try? decode(data, maxVersion: maxVersion)
        else { return EmojiCatalog(categories: []) }
        return catalog
    }

    /// Keeps entries at or under `maxVersion` that pass the Server's
    /// single-emoji rule, in its normalized spelling.
    static func decode(_ data: Data, maxVersion: Double) throws -> EmojiCatalog {
        let resource = try JSONDecoder().decode(Resource.self, from: data)
        let categories = resource.groups.map { group in
            EmojiCategory(name: group.name, entries: group.emoji.compactMap { row in
                guard (Double(row.version) ?? .infinity) <= maxVersion,
                      let emoji = ReactionEmoji.normalized(row.emoji)
                else { return nil }
                return EmojiEntry(
                    emoji: emoji,
                    name: row.name,
                    words: Self.words(row.name) + Self.words(row.keywords),
                    supportsSkinTones: row.skinTones
                )
            })
        }
        return EmojiCatalog(categories: categories.filter { !$0.entries.isEmpty })
    }

    /// The entry for an emoji, whatever its spelling or skin tone.
    func entry(for emoji: String) -> EmojiEntry? {
        let base = EmojiSkinTone.base(of: emoji)
        return index[base] ?? index[emoji]
    }

    // MARK: Search

    /// Entries every query word prefixes a word of, best first: the emoji
    /// named exactly that, then those matching by name, then by keyword, each
    /// run in catalog order. "dino" finds 🦕 and 🦖 by keyword.
    func search(_ query: String) -> [EmojiEntry] {
        let terms = Self.words(query)
        guard !terms.isEmpty else { return [] }
        var tiers: [[EmojiEntry]] = [[], [], []]
        for entry in categories.lazy.flatMap(\.entries) {
            guard Self.prefixes(terms, entry.words) else { continue }
            let nameWords = Self.words(entry.name)
            let tier = nameWords == terms ? 0 : Self.prefixes(terms, nameWords) ? 1 : 2
            tiers[tier].append(entry)
        }
        return tiers.flatMap(\.self)
    }

    private static func prefixes(_ terms: [String], _ words: [String]) -> Bool {
        terms.allSatisfy { term in words.contains { $0.hasPrefix(term) } }
    }

    static func words(_ text: String) -> [String] {
        text.lowercased()
            .components(separatedBy: CharacterSet.alphanumerics.inverted)
            .filter { !$0.isEmpty }
    }

    private struct Resource: Decodable {
        let groups: [Group]

        struct Group: Decodable {
            let name: String
            let emoji: [Row]
        }

        /// `[emoji, name, emoji version, skin tones (1/0), extra keywords]`.
        struct Row: Decodable {
            let emoji: String
            let name: String
            let version: String
            let skinTones: Bool
            let keywords: String

            init(from decoder: Decoder) throws {
                var row = try decoder.unkeyedContainer()
                emoji = try row.decode(String.self)
                name = try row.decode(String.self)
                version = try row.decode(String.self)
                skinTones = try row.decode(Int.self) == 1
                keywords = try row.decode(String.self)
            }
        }
    }
}
