import Foundation
import SwiftUI

/// The app icon set: hugeicons stroke-rounded, the same family the App's React
/// surfaces import, so the two clients draw one vocabulary.
///
/// Every case's raw value is the hugeicons name, and the geometry is generated
/// straight from the family — this enum is only the phone's pick of which names
/// it shows. SF Symbols stay where the system owns the grammar: navigation
/// backs, disclosure chevrons, selection checkmarks, and `Menu` labels, which
/// read as platform affordances rather than product iconography.
public enum HausIconName: String, CaseIterable, Sendable {
    case account = "UserIcon"
    case agents = "CpuIcon"
    case alert = "AlertCircleIcon"
    case appearance = "Sun03Icon"
    case archive = "ArchiveIcon"
    /// The mark on a Message that asks a named human for a decision.
    case ask = "BubbleChatQuestionIcon"
    case arrowDown = "ArrowDown01Icon"
    case attachment = "Attachment01Icon"
    case calendar = "Calendar03Icon"
    case camera = "Camera01Icon"
    /// App and plugin references — the App draws both with the same plug.
    case capability = "PlugIcon"
    case channel = "HashtagIcon"
    /// A brand mark the App names by hand in its capability appearance
    /// overrides, where the plug is too generic for a browser everyone knows.
    case chrome = "ChromeIcon"
    case close = "Cancel01Icon"
    case complete = "CheckmarkCircle02Icon"
    case computer = "ComputerIcon"
    case description = "TextAlignLeftIcon"
    case document = "File01Icon"
    case email = "Mail01Icon"
    case folder = "Folder01Icon"
    /// The brand mark the App's Skill appearance overrides give the GitHub
    /// Skills, in place of the sparkles.
    case github = "Github01Icon"
    case handle = "AtIcon"
    case help = "HelpCircleIcon"
    case identity = "UserCheck01Icon"
    case image = "Image01Icon"
    case info = "InformationCircleIcon"
    case magic = "AiMagicIcon"
    case media = "Album02Icon"
    case members = "UserMultiple02Icon"
    case menu = "Menu02Icon"
    case more = "MoreHorizontalIcon"
    /// A Thread the reader follows, and the press that stops it. The
    /// App's Thread header draws the same pair.
    case notification = "Notification01Icon"
    case notificationOff = "NotificationOff01Icon"
    case pdf = "Pdf01Icon"
    case permissions = "UserLock01Icon"
    case plus = "PlusSignIcon"
    case pullRequest = "GitPullRequestIcon"
    case search = "Search01Icon"
    // Not `ArrowUp01Icon`, which is a bare chevron: the family numbers its
    // arrows by shape, not by weight, and only `02` carries a shaft.
    case send = "ArrowUp02Icon"
    case server = "ServerStack01Icon"
    case settings = "Settings01Icon"
    // The App keeps a local solid copy because its solid package has no such
    // export; the stroke-rounded family the phone draws from carries the name.
    case skill = "AiSparklesIcon"
    case tasks = "CheckListIcon"
    case terminal = "CommandLineIcon"
    case video = "Video01Icon"
    case voice = "AudioWave01Icon"
    case website = "Globe02Icon"
}

/// One app icon, drawn at a point size the way an SF Symbol would be.
///
/// The geometry is a unit-square path rather than a font glyph, so unlike
/// `Image(systemName:)` it does not track the text baseline or Dynamic Type on
/// its own. Callers place it in a fixed box; anywhere it sits inline with text,
/// that box is what aligns it.
public struct HausIcon: View {
    private let name: HausIconName
    private let size: CGFloat
    private let weight: CGFloat

    /// - Parameter weight: stroke width on the 24pt hugeicons grid. The family
    ///   draws at `1.5`, which reads lighter beside SF Symbols' medium; chrome
    ///   that sits next to bold text asks for more.
    public init(_ name: HausIconName, size: CGFloat, weight: CGFloat = 1.5) {
        self.name = name
        self.size = size
        self.weight = weight
    }

    public var body: some View {
        HugeiconGlyph(subpaths: UIIconCatalog.shared.subpaths(for: name, weight: weight))
            .frame(width: size, height: size)
            .accessibilityHidden(true)
    }
}

/// The bundled app icon geometry.
///
/// `Sources/HausUI/Resources/ui-icons.json`, generated by
/// `bun apps/ios-swift/scripts/generate-ui-icon-paths.ts`. It is around 80 KiB
/// — small enough to decode on first use rather than asynchronously, so an icon
/// never pops in after its row has already drawn. That is the whole reason this
/// is not `ChannelIconCatalog`, which carries 1.8 MiB of pictorial glyphs and
/// has to load off the main actor behind a fallback.
@MainActor
final class UIIconCatalog {
    static let shared = UIIconCatalog()

    private lazy var pathData: [String: [HugeiconResourceSubpath]] = Self.decode()
    private var parsed: [Key: [HugeiconSubpath]] = [:]

    private struct Key: Hashable {
        let name: HausIconName
        let weight: CGFloat
    }

    private init() {}

    func subpaths(for name: HausIconName, weight: CGFloat) -> [HugeiconSubpath] {
        let key = Key(name: name, weight: weight)
        if let cached = parsed[key] { return cached }

        let subpaths = (pathData[name.rawValue] ?? []).compactMap { resource in
            Self.subpath(resource, weight: weight)
        }
        parsed[key] = subpaths
        return subpaths
    }

    private static func subpath(
        _ resource: HugeiconResourceSubpath,
        weight: CGFloat
    ) -> HugeiconSubpath? {
        // Hugeicons draws in a 24x24 viewBox; the renderer scales the unit
        // square to whatever box size the caller asked for.
        let path = SVGPathData.path(from: resource.d)
            .applying(CGAffineTransform(scaleX: 1.0 / 24, y: 1.0 / 24))
        guard !path.isEmpty else { return nil }

        return HugeiconSubpath(
            path: path,
            evenOdd: resource.rule == "evenodd",
            // The family is stroked chrome throughout, so an entry without a
            // stroke width is filled geometry and keeps its own shape.
            stroke: resource.strokeWidth == nil ? nil : HugeiconSubpath.Stroke(
                width: weight / 24,
                cap: resource.cap == "round" ? .round : .butt,
                join: resource.join == "round" ? .round : .miter
            )
        )
    }

    private static func decode() -> [String: [HugeiconResourceSubpath]] {
        guard let url = Bundle.module.url(forResource: "ui-icons", withExtension: "json"),
              let data = try? Data(contentsOf: url, options: .mappedIfSafe),
              let resource = try? JSONDecoder().decode(Resource.self, from: data)
        else { return [:] }
        return resource.icons
    }

    private struct Resource: Decodable {
        let icons: [String: [HugeiconResourceSubpath]]
    }
}

#Preview("App icons") {
    VStack(alignment: .leading, spacing: 14) {
        ForEach(HausIconName.allCases, id: \.self) { name in
            HStack(spacing: 12) {
                HausIcon(name, size: 21)
                HausIcon(name, size: 21, weight: 2)
                Image(systemName: "square.dashed").font(.system(size: 21))
                Text(name.rawValue).font(.subheadline)
            }
        }
    }
    .padding()
}
