// Generated by scripts/agent-html-tokens/generate-ios-tokens.ts — do not edit.
// Regenerate with `bun run gen:ios-tokens`.

/// Resolved values of the published agent-HTML token contract
/// (apps/website/src/agent-html/tokens.ts), snapshotted per color scheme:
/// the taught vocabulary, then the derived chart chrome. That list is the
/// whole contract — there is no alias tail.
///
/// Every value here is the web's, with one deliberate exception the sandbox
/// document applies on top: `--app-ui-font-size` is re-declared from the
/// current Dynamic Type size, because the web ties it to the web chat's 14px
/// body and the iOS transcript is SF `.body` at 17pt. See
/// `VisualTypography`.
public enum AgentHtmlTokens {
    public static let dark: [AgentHtmlToken] = [
        AgentHtmlToken(name: "--font-sans", value: "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'"),
        AgentHtmlToken(name: "--font-mono", value: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"),
        AgentHtmlToken(name: "--app-ui-font-size", value: "0.875rem"),
        AgentHtmlToken(name: "--background", value: "#060607"),
        AgentHtmlToken(name: "--surface", value: "#18181b"),
        AgentHtmlToken(name: "--surface-secondary", value: "#232325"),
        AgentHtmlToken(name: "--surface-tertiary", value: "#262728"),
        AgentHtmlToken(name: "--foreground", value: "#fcfcfc"),
        AgentHtmlToken(name: "--muted-foreground", value: "#9f9fa9"),
        AgentHtmlToken(name: "--foreground-tertiary", value: "#81818a"),
        AgentHtmlToken(name: "--border", value: "#28282c"),
        AgentHtmlToken(name: "--border-strong", value: "#434345"),
        AgentHtmlToken(name: "--accent", value: "#0485f7"),
        AgentHtmlToken(name: "--accent-foreground", value: "#2e90f9"),
        AgentHtmlToken(name: "--accent-bg", value: "#0485f71f"),
        AgentHtmlToken(name: "--success", value: "#17c964"),
        AgentHtmlToken(name: "--success-foreground", value: "#40ce71"),
        AgentHtmlToken(name: "--success-bg", value: "#17c9641f"),
        AgentHtmlToken(name: "--warning", value: "#f7b750"),
        AgentHtmlToken(name: "--warning-foreground", value: "#f8bd62"),
        AgentHtmlToken(name: "--warning-bg", value: "#f7b7501f"),
        AgentHtmlToken(name: "--error", value: "#db3b3e"),
        AgentHtmlToken(name: "--error-foreground", value: "#e04f4e"),
        AgentHtmlToken(name: "--error-bg", value: "#db3b3e26"),
        AgentHtmlToken(name: "--chart-1", value: "#3987e5"),
        AgentHtmlToken(name: "--chart-2", value: "#d95926"),
        AgentHtmlToken(name: "--chart-3", value: "#199e70"),
        AgentHtmlToken(name: "--chart-4", value: "#c98500"),
        AgentHtmlToken(name: "--chart-5", value: "#9f9fa9"),
        AgentHtmlToken(name: "--radius", value: "9px"),
        AgentHtmlToken(name: "--radius-card", value: "18px"),
        AgentHtmlToken(name: "--pad-sm", value: "7.5px"),
        AgentHtmlToken(name: "--pad-md", value: "11.25px"),
        AgentHtmlToken(name: "--pad-lg", value: "15px"),
        AgentHtmlToken(name: "--gap-xs", value: "3.75px"),
        AgentHtmlToken(name: "--gap-sm", value: "7.5px"),
        AgentHtmlToken(name: "--gap-md", value: "11.25px"),
        AgentHtmlToken(name: "--gap-lg", value: "15px"),
        AgentHtmlToken(name: "--chart-grid", value: "#43434594"),
        AgentHtmlToken(name: "--chart-label", value: "#9f9fa9db"),
    ]

    public static let light: [AgentHtmlToken] = [
        AgentHtmlToken(name: "--font-sans", value: "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'"),
        AgentHtmlToken(name: "--font-mono", value: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"),
        AgentHtmlToken(name: "--app-ui-font-size", value: "0.875rem"),
        AgentHtmlToken(name: "--background", value: "#f9f9fa"),
        AgentHtmlToken(name: "--surface", value: "#ffffff"),
        AgentHtmlToken(name: "--surface-secondary", value: "#e9e9ea"),
        AgentHtmlToken(name: "--surface-tertiary", value: "#e5e5e6"),
        AgentHtmlToken(name: "--foreground", value: "#18181b"),
        AgentHtmlToken(name: "--muted-foreground", value: "#71717a"),
        AgentHtmlToken(name: "--foreground-tertiary", value: "#7f7f87"),
        AgentHtmlToken(name: "--border", value: "#dedede"),
        AgentHtmlToken(name: "--border-strong", value: "#c6c6c7"),
        AgentHtmlToken(name: "--accent", value: "#0485f7"),
        AgentHtmlToken(name: "--accent-foreground", value: "#1e63ae"),
        AgentHtmlToken(name: "--accent-bg", value: "#0485f726"),
        AgentHtmlToken(name: "--success", value: "#17c964"),
        AgentHtmlToken(name: "--success-foreground", value: "#2b7745"),
        AgentHtmlToken(name: "--success-bg", value: "#17c96426"),
        AgentHtmlToken(name: "--warning", value: "#f5a524"),
        AgentHtmlToken(name: "--warning-foreground", value: "#855f2e"),
        AgentHtmlToken(name: "--warning-bg", value: "#f5a52426"),
        AgentHtmlToken(name: "--error", value: "#ff383c"),
        AgentHtmlToken(name: "--error-foreground", value: "#a43433"),
        AgentHtmlToken(name: "--error-bg", value: "#ff383c26"),
        AgentHtmlToken(name: "--chart-1", value: "#2a78d6"),
        AgentHtmlToken(name: "--chart-2", value: "#eb6834"),
        AgentHtmlToken(name: "--chart-3", value: "#1baf7a"),
        AgentHtmlToken(name: "--chart-4", value: "#eda100"),
        AgentHtmlToken(name: "--chart-5", value: "#9f9fa9"),
        AgentHtmlToken(name: "--radius", value: "9px"),
        AgentHtmlToken(name: "--radius-card", value: "18px"),
        AgentHtmlToken(name: "--pad-sm", value: "7.5px"),
        AgentHtmlToken(name: "--pad-md", value: "11.25px"),
        AgentHtmlToken(name: "--pad-lg", value: "15px"),
        AgentHtmlToken(name: "--gap-xs", value: "3.75px"),
        AgentHtmlToken(name: "--gap-sm", value: "7.5px"),
        AgentHtmlToken(name: "--gap-md", value: "11.25px"),
        AgentHtmlToken(name: "--gap-lg", value: "15px"),
        AgentHtmlToken(name: "--chart-grid", value: "#c6c6c794"),
        AgentHtmlToken(name: "--chart-label", value: "#71717adb"),
    ]
}
