import type { components, operations, paths } from './generated/openapi.d.ts';

export type { components, operations, paths, webhooks } from './generated/openapi.d.ts';

export type HausApiComponents = components;
export type HausApiPaths = paths;
export type HausApiOperations = operations;

export type HausApiSchema<Name extends keyof components['schemas']> = components['schemas'][Name];

export type HausArtifact = HausApiSchema<'ChatArtifact'>;
export type HausAgentApiError = HausApiSchema<'AgentApiError'>;
export type HausAgentChannel = HausApiSchema<'AgentChannel'>;
export type HausAgentChannelMember = HausApiSchema<'AgentChannelMember'>;
export type HausAgentChannelMembers = HausApiSchema<'AgentChannelMembers'>;
export type HausAgentHistoryResponse = HausApiSchema<'AgentHistoryResponse'>;
export type HausAgentManualSearchResponse = HausApiSchema<'AgentManualSearchResponse'>;
export type HausAgentManualTopic = HausApiSchema<'AgentManualTopic'>;
export type HausAgentMessage = HausApiSchema<'AgentMessage'>;
export type HausAgentSearchResult = HausApiSchema<'AgentSearchResult'>;
export type HausAgentSearchResultList = HausApiSchema<'AgentSearchResultList'>;
export type HausAgentSendApiError = HausApiSchema<'AgentSendApiError'>;
export type HausAgentSendRequest = HausApiSchema<'AgentSendRequest'>;
export type HausAgentSendResponse = HausApiSchema<'AgentSendResponse'>;
export type HausAgentServerInfo = HausApiSchema<'AgentServerInfo'>;
export type HausChat = HausApiSchema<'Chat'>;
export type HausChatEvent = HausApiSchema<'ChatEvent'>;
export type HausChatMessage = HausApiSchema<'ChatMessage'>;
export type HausChatMessageReceipt = HausApiSchema<'ChatMessageReceipt'>;
export type HausChatResponse = HausApiSchema<'ChatResponse'>;
export type HausChatTimelinePage = HausApiSchema<'ChatTimelinePage'>;
export type HausClearChatReceipt = HausApiSchema<'ClearChatReceipt'>;
export type HausCreateChatRequest = HausApiSchema<'CreateChatRequest'>;
export type HausCreateDeliveryRequest = HausApiSchema<'CreateDeliveryRequest'>;
export type HausCreateMessageRequest = HausApiSchema<'CreateMessageRequest'>;
export type HausDeleteResponseReceipt = HausApiSchema<'DeleteResponseReceipt'>;
export type HausEnsureThreadRequest = HausApiSchema<'EnsureThreadRequest'>;
export type HausEventList = HausApiSchema<'EventList'>;
export type HausListChatsResponse = HausApiSchema<'ListChatsResponse'>;
export type HausListMessagesResponse = HausApiSchema<'ListMessagesResponse'>;
export type HausListResponsesResponse = HausApiSchema<'ListResponsesResponse'>;
export type HausMarkReadRequest = HausApiSchema<'MarkReadRequest'>;
export type HausMessageReaction = HausApiSchema<'MessageReaction'>;
export type HausMessageAsk = HausApiSchema<'MessageAsk'>;
export type HausMessageTask = HausApiSchema<'MessageTask'>;
export type HausTaskActor = HausApiSchema<'TaskActor'>;
export type HausTaskLabel = HausApiSchema<'TaskLabel'>;
export type HausResponseActivity = HausApiSchema<'ResponseActivity'>;
export type HausResponseEvidence = HausApiSchema<'ResponseEvidence'>;
export type HausSetThreadFollowRequest = HausApiSchema<'SetThreadFollowRequest'>;
export type HausThreadSummary = HausApiSchema<'ThreadSummary'>;
export type HausTurnPromptEvidence = HausApiSchema<'TurnPromptEvidence'>;
export type HausTurnFileChange = HausApiSchema<'TurnFileChange'>;
export type HausTurnFileChangeEvidence = HausApiSchema<'TurnFileChangeEvidence'>;
export type HausUpsertArtifactRequest = HausApiSchema<'UpsertArtifactRequest'>;
export type HausUpsertResponseActivityRequest = HausApiSchema<'UpsertResponseActivityRequest'>;
export type HausUpsertResponseRequest = HausApiSchema<'UpsertResponseRequest'>;

export * from './agent.ts';
export * from './agent-activity.ts';
export * from './agent-creation.ts';
export * from './agent-execution.ts';
export * from './agent-runner.ts';
export * from './agent-workspace-files.ts';
export * from './app-protocol.ts';
export * from './ask.ts';
export * from './ask-shared.ts';
export * from './attachments.ts';
export * from './automation.ts';
export * from './avatar.ts';
export * from './avatar-generation.ts';
export * from './chat.ts';
export * from './chat-engagement.ts';
export * from './chat-last-message.ts';
export * from './cloud-agent.ts';
export * from './cloud-agent-shared.ts';
export * from './computer-inventory-refresh.ts';
export * from './computer-runtime.ts';
export * from './computer-system-events.ts';
export * from './computer-update.ts';
export * from './development-chat-demos.ts';
export * from './haus-agent-version.ts';
export * from './haus-release.ts';
export * from './manual.ts';
export * from './mcp.ts';
export * from './membership.ts';
export * from './mentions.ts';
export * from './message-routing.ts';
export * from './participant-handle.ts';
export * from './reminders.ts';
export * from './rich-references.ts';
export * from './runtime/contracts.ts';
export * from './runtime/identity.ts';
export * from './runtime/mcp.ts';
export * from './runtime/model-identity.ts';
export * from './runtime/model-providers.ts';
export * from './runtime/pane-links.ts';
export * from './runtime/routes.ts';
export * from './runtime/runtime-aliases.ts';
export * from './runtime/skill-hub.ts';
export * from './runtime/skills.ts';
export * from './runtime/tool-setup.ts';
export * from './server-events.ts';
export * from './stats.ts';
export * from './task.ts';
export * from './task-shared.ts';
export * from './triggers.ts';
export * from './widgets/contracts.ts';
