/**
 * Snapshot the published agent-HTML token contract for iOS.
 *
 * The web reads these values off `getComputedStyle(document.documentElement)`;
 * iOS has no browser to read from, so this resolves the same names statically
 * out of the stylesheets the web app imports and writes them into the Swift
 * package. Run it with `bun run gen:ios-tokens`; the checked-in file is
 * drift-tested, so a theme change that is not regenerated fails CI.
 */

import { agentHtmlTokenNames } from '../../apps/website/src/agent-html/tokens.ts';
import { type Cascade, collectCascade, type Scheme } from './css-cascade.ts';
import { resolveExpression, resolveVariable } from './resolve-token.ts';

const REPO = new URL('../..', import.meta.url).pathname;

const WEB = `${REPO}apps/website`;

/**
 * The token-declaring subset of the `@import` order in
 * `apps/website/src/styles/global.css`, in that order.
 * `artifact-tokens.css` is `layer(theme)` like Pro's chart block and imported
 * after it, so equal-specificity declarations there win on source order.
 *
 * Three of that file's imports are deliberately left out: `slot-text/style.css`,
 * `features/chats/chat.css`, and `features/shell/shell.css`. They are feature
 * stylesheets — component rules and their own private variables — and declare no
 * name in the published contract (`apps/website/src/agent-html/tokens.ts`), so
 * reading them could only change a resolved value by accident. Adding a
 * published token to one of them is what would make it belong here.
 */
const SOURCES = [
    `${WEB}/node_modules/tailwindcss/theme.css`,
    `${WEB}/node_modules/@heroui/styles/dist/themes/shared/theme.css`,
    `${WEB}/node_modules/@heroui/styles/dist/themes/default/variables.css`,
    `${WEB}/node_modules/@heroui-pro/react/dist/css/index.css`,
    `${WEB}/src/styles/product-tokens.css`,
    `${WEB}/src/styles/artifact-tokens.css`,
    `${WEB}/src/styles/default-theme.css`,
];

export const OUTPUT_PATH = `${REPO}apps/ios-swift/Sources/HausUI/Visuals/AgentHtmlTokens.generated.swift`;

/** Mirrors `hostRoleOverrides` in `apps/website/src/agent-html/tokens.ts`. */
const HOST_ROLES: Record<string, string> = {
    '--accent-foreground': '--accent-soft-foreground',
    '--radius': '--radius-control',
    '--success-foreground': '--success-soft-foreground',
    '--warning-foreground': '--warning-soft-foreground',
};

/**
 * Chart chrome the web derives rather than snapshots, resolved here so the
 * Swift table needs no runtime `var()` support.
 */
const DERIVED: Record<string, string> = {
    '--chart-grid': 'color-mix(in srgb, var(--border-strong) 58%, transparent)',
    '--chart-label': 'color-mix(in srgb, var(--muted-foreground) 86%, transparent)',
};

const SCHEMES: Scheme[] = ['dark', 'light'];

export interface ResolvedToken {
    name: string;
    value: string;
}

/**
 * Every name the web snapshot emits — the taught vocabulary plus the derived
 * chart chrome — in contract order.
 */
export function resolveTokens(scheme: Scheme): ResolvedToken[] {
    const cascade: Cascade = collectCascade(SOURCES, scheme);
    const published = agentHtmlTokenNames.map((name) => ({
        name,
        value: resolveVariable(cascade, HOST_ROLES[name] ?? name),
    }));
    const derived = Object.entries(DERIVED).map(([name, expression]) => ({
        name,
        value: resolveExpression(cascade, name, expression),
    }));

    return [...published, ...derived];
}

export function renderSwiftSource(): string {
    const tables = SCHEMES.map((scheme) => renderTable(scheme)).join('\n\n');

    return `// Generated by scripts/agent-html-tokens/generate-ios-tokens.ts — do not edit.
// Regenerate with \`bun run gen:ios-tokens\`.

/// Resolved values of the published agent-HTML token contract
/// (apps/website/src/agent-html/tokens.ts), snapshotted per color scheme:
/// the taught vocabulary, then the derived chart chrome. That list is the
/// whole contract — there is no alias tail.
///
/// Every value here is the web's, with one deliberate exception the sandbox
/// document applies on top: \`--app-ui-font-size\` is re-declared from the
/// current Dynamic Type size, because the web ties it to the web chat's 14px
/// body and the iOS transcript is SF \`.body\` at 17pt. See
/// \`VisualTypography\`.
public enum AgentHtmlTokens {
${tables}
}
`;
}

function renderTable(scheme: Scheme): string {
    const entries = resolveTokens(scheme)
        .map((token) => `        ${renderEntry(token)},`)
        .join('\n');

    return `    public static let ${scheme}: [AgentHtmlToken] = [\n${entries}\n    ]`;
}

function renderEntry(token: ResolvedToken): string {
    return `AgentHtmlToken(name: ${swiftString(token.name)}, value: ${swiftString(token.value)})`;
}

function swiftString(value: string): string {
    return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

if (import.meta.main) {
    await Bun.write(OUTPUT_PATH, renderSwiftSource());
    console.log(`Wrote ${OUTPUT_PATH}`);
}
