/**
 * Render the resolved agent-HTML token tables as the `@haus/api` snapshot.
 *
 * Haus Computer renders agent visuals headlessly from a compiled binary that
 * cannot read the website's stylesheets out of `node_modules`, so it reads the
 * same per-scheme values the iOS table carries from
 * `packages/haus-api/src/widgets/visual/tokens.generated.ts`. Both files are
 * written by one `bun run gen:ios-tokens` run from one `resolveTokens` pass.
 */

import type { Scheme } from './css-cascade.ts';

const REPO = new URL('../..', import.meta.url).pathname;

export const API_OUTPUT_PATH = `${REPO}packages/haus-api/src/widgets/visual/tokens.generated.ts`;

export interface ResolvedToken {
    name: string;
    value: string;
}

export type ResolvedTables = Record<Scheme, ResolvedToken[]>;

const SCHEMES: Scheme[] = ['dark', 'light'];

export function renderApiTokensSource(tables: ResolvedTables): string {
    const schemes = SCHEMES.map((scheme) => renderScheme(scheme, tables[scheme])).join('\n');

    return `// Generated by scripts/agent-html-tokens/generate-ios-tokens.ts — do not edit.
// Regenerate with \`bun run gen:ios-tokens\`.

/**
 * Resolved values of the published agent-HTML token contract
 * (apps/website/src/agent-html/tokens.ts), snapshotted per color scheme: the
 * taught vocabulary, then the derived chart chrome, in contract order. Dark is
 * the bare \`:root\` cascade, light is \`:root[data-theme='light']\`.
 *
 * Values are folded to literals (no \`var()\`, \`calc()\`, \`min()\` or
 * \`color-mix()\`), the same table the iOS app ships. Read it through
 * \`./tokens.ts\`.
 */
export const agentHtmlTokenSnapshot = {
${schemes}} as const;
`;
}

function renderScheme(scheme: Scheme, tokens: ResolvedToken[]): string {
    const entries = tokens
        .map((token) => `        '${token.name}': ${tsString(token.value)},`)
        .join('\n');

    return `    ${scheme}: {\n${entries}\n    },\n`;
}

/** Biome's single-quote style, falling back to double quotes around a `'`. */
function tsString(value: string): string {
    const escaped = value.replace(/\\/g, '\\\\');

    if (!escaped.includes("'")) {
        return `'${escaped}'`;
    }

    return `"${escaped.replace(/"/g, '\\"')}"`;
}
