import Foundation
import HausModels

/// Eight models from a real Cursor `models.list()` read, mapped by Computer's
/// `model-catalog-mapping.ts` and kept in Cursor's order.
enum CloudAgentModelFixture {
    static let catalogJSON = #"{"models":[{"description":null,"displayName":"Grok 4.7","effort":{"defaultValue":"high","options":[{"displayName":"Low","value":"low"},{"displayName":"Medium","value":"medium"},{"displayName":"High","value":"high"},{"displayName":"Extra High","value":"xhigh"}],"providerParamId":"reasoning_effort"},"family":"grok","fast":{"defaultValue":true},"id":"grok-4.7","order":0},{"description":null,"displayName":"Composer 2.5","effort":null,"family":"composer","fast":{"defaultValue":true},"id":"composer-2.5","order":2},{"description":null,"displayName":"Claude Opus 5.5","effort":{"defaultValue":"medium","options":[{"displayName":"Low","value":"low"},{"displayName":"Medium","value":"medium"},{"displayName":"High","value":"high"},{"displayName":"Extra High","value":"xhigh"},{"displayName":"Max","value":"max"}],"providerParamId":"effort"},"family":"claude","fast":{"defaultValue":false},"id":"claude-opus-5-5","order":3},{"description":null,"displayName":"GPT-5.6 Sol","effort":{"defaultValue":"medium","options":[{"displayName":"None","value":"none"},{"displayName":"Low","value":"low"},{"displayName":"Medium","value":"medium"},{"displayName":"High","value":"high"},{"displayName":"Extra High","value":"xhigh"},{"displayName":"Max","value":"max"}],"providerParamId":"reasoning"},"family":"gpt","fast":{"defaultValue":false},"id":"gpt-5.6-sol","order":6},{"description":null,"displayName":"Gemini 3.8 Flash","effort":{"defaultValue":"high","options":[{"displayName":"Low","value":"low"},{"displayName":"Medium","value":"medium"},{"displayName":"High","value":"high"}],"providerParamId":"reasoning_effort"},"family":"gemini","fast":null,"id":"gemini-3.8-flash","order":11},{"description":null,"displayName":"Claude Opus 4.5","effort":null,"family":"claude","fast":null,"id":"claude-opus-4-5","order":23},{"description":null,"displayName":"Kimi K3","effort":{"defaultValue":"max","options":[{"displayName":"Low","value":"low"},{"displayName":"High","value":"high"},{"displayName":"Max","value":"max"}],"providerParamId":"reasoning"},"family":"kimi","fast":null,"id":"kimi-k3","order":38},{"description":null,"displayName":"GLM 5.2","effort":{"defaultValue":"high","options":[{"displayName":"High","value":"high"},{"displayName":"Max","value":"max"}],"providerParamId":"reasoning"},"family":"glm","fast":null,"id":"glm-5.2","order":40}],"refreshedAt":"2026-10-02T10:00:00Z"}"#

    static func catalog() throws -> CloudAgentModelCatalog {
        try HausJSON.decoder().decode(CloudAgentModelCatalog.self, from: Data(catalogJSON.utf8))
    }
}
